### PR TITLE
Adding jedi rotation scripts

### PR DESCRIPTION
**Pull request by vishnuchalla**
## Type of change

- [ ] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Adding Jedi rotation scripts.

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
Tested its working on the jump host.

### CODE REVIEW

**Review by jtaleric — COMMENTED** [review]
Wonder how advanced we should make this -- ie, read from individual gcal's from the user's to determine PTO and likely availability.

**Comment by vishnuchalla** [comment]
> Wonder how advanced we should make this -- ie, read from individual gcal's from the user's to determine PTO and likely availability.

If someone wants to override the current schedule they can simply edit the rotation file in our jump host as mentioned in the `README.md`.  I think its better to keep this step as manual, so that there will be proper communication and agreement between the two parties planning to perform overrides.

**Comment by vishnuchalla** [comment]
@rsevilla87 @jtaleric just a gentle reminder on this one.

**Comment by vishnuchalla** [comment]
Merging it as these are non-impacting changes and working as of now. We can add more if required in future.

**Pull request merged**
