### PR TITLE
Hosting jedi schedule as a HTML table

### PR DESCRIPTION
**Pull request by vishnuchalla**
## Type of change

- [ ] Refactor
- [x] New feature
- [ ] Bug fix
- [x] Optimization
- [ ] Documentation Update

## Description
Hosting jedi rotation schedule as a HTML table.

## Related Tickets & Documents

- Closes # https://issues.redhat.com/browse/PERFSCALE-3375?filter=-1

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
Tested by hosting the content here: http://ocp-intlab-grafana.rdu2.scalelab.redhat.com:3030/

### CODE REVIEW

**Review by dry923 — APPROVED** [review]
LGTM!

**Review by paigerube14 — APPROVED** [review]
/lgtm

**Review by afcollins — APPROVED** [review]
Wondering if there is a cleaner approach than in-lined raw HTML, but if it works, it works. ✅

**Comment by vishnuchalla** [comment]
> Wondering if there is a cleaner approach than in-lined raw HTML, but if it works, it works. ✅

Definitely there is. But needs heavy time investment to go away from this simple solution.

**Pull request merged**
